[project]
authors = ["PaulKMueller <paul.mueller@quantco.com>"]
channels = ["conda-forge", "https://conda.prod.quantco.cloud/get/qc-internal"]
description = "Add a short description here"
name = "open_qr"
platforms = ["osx-arm64"]
version = "0.1.0"

[tasks]

[dependencies]
streamlit = ">=1.39.0,<2"
segno = ">=1.6.1,<2"
